### ISSUE TITLE
router导致一个体验上的问题

### ISSUE THREAD

**Issue by joket1999** [canfoo/react-taopiaopiao#1]
当切换底部nav时，肯定会改变路由，比如我在nav的两个页面之间频繁切换，这里就产生了很多history。
如果在手机上或者在浏览器上，这样的话就能通过 “返回键” 控制，通过层层的返回才能到达第一次进来的页面，或者在类似微信这样的一个环境上，很难退出，只能按关闭。

**Comment by canfoo** [comment]
因为为了方便学习（很多童鞋都只是在chrome使用），所以我加了底部返回功能。这个项目其实应该放在app里面的，如果要实现关闭退出页面功能，可以通过app交互实现。如果在微信里面，也可以调用微信的api进行关闭页面。这样就可以解决你说的体验问题了，但是在ios上，这个问题确实可以不用考虑的。这个你应该知道吧

**Comment by joket1999** [comment]
@canfoo 其实我觉得在nav这类的菜单，不应该改变路由来更新页面。通过改变组件的名字来更新，比如
```
let ComponentName = 'Cinema'; // Home、Me
<ComponentName/>
```

**Comment by canfoo** [comment]
你说的这种方式，就是tab切换吧？这得看应用场景和数据复杂度咯～
